version: '3'
services:
  sommercamp-backend:
    container_name: sommercamp-backend
    build:
      context: .
      dockerfile: server.dockerfile
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    ports:
      - "8000:8000"

  sommercamp-db:
    container_name: sommercamp-db
    image: arm64v8/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: Hallo123
    ports:
          - "3306:3306"
